---
title: "Lucia's Website"
---

## Introduction

Welcome to my page! 

My name is Lucia, and I am a 2nd year MPH student at Columbia University in the Epidemiology department with a certificate in Infectious Disease Epidemiology. 

This website was made as an assignment through P8105 - Data Science, and tests my R and programming knowledge. 

Check out my [about](about.html) page to see information about my academic and professional background, and feel free to peruse the links in the navigation bar to contact me. 

## Recommendations
Outside of epidemiology and public health, I enjoy a lot of artsy things! 

A few books I've read recently and enjoyed:

* Beasts of a Little Land by **Juhea Kim** 

* The Language of Fanaticism: Cultish by **Amanda Montell**

* Demon Copperhead by **Barbara Kingsolver**

And some songs I've had on repeat:

* Psychedelic Switch by **Carly Rae Jepsen**

* Abstract (Psychopomp) by **Hozier**

* get him back! by **Olivia Rodrigo**

And some movies I love rewatching:

* Gifted *(2017) *

* Kung Fu Panda *(2008)*

* 